### ISSUE TITLE
CLI-1389: "push:artifact" command has support for multiple git urls using acli config file but not supported in file.

### ISSUE THREAD

**Issue by joshirohit100** [acquia/cli#1788]
acli `push:artifact` command supports multiple git urls and as per https://github.com/acquia/cli/blob/main/src/Command/Push/PushArtifactCommand.php#L164 config can be done using acli config file (acquic-cli.yml) but looks like code for this is not supported as AcquiaCliConfig only supports one key `cloud_app_uuid`

https://github.com/acquia/cli/blob/main/src/Config/AcquiaCliConfig.php#L23

This is my sample acli config file -
```
cloud_app_uuid: APPIDHERE
push:
  artifact:
    destination_git_urls:
      - GITURL1HERE
      - GITURL2HERE
```
