### ISSUE TITLE
OpenAPI spec: VCS URI format is incorrect

### ISSUE THREAD

**Issue by manarth** [acquia/cli#769]
The spec defines the VCS uri as follows:

```yaml
        url:
          type: string
          description: The VCS url.
          format: uri
```

An example response from the API could be:

```
            "url": "myapplication@svn-12345.prod.hosting.acquia.com:myapplication.git"
```

The API responses contain an SSH-formatted Git identity, which does not match the specification format of `uri`.
